// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A multiple choice question (MCQ) generation AI agent.
 *
 * - generateMCQ - A function that handles the MCQ generation process.
 * - GenerateMCQInput - The input type for the generateMCQ function.
 * - GenerateMCQOutput - The return type for the generateMCQ function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateMCQInputSchema = z.object({
  topic: z.string().describe('The topic to generate MCQs for.'),
  numQuestions: z.number().describe('The number of MCQs to generate.'),
  grade: z.string().describe('The grade of the student.').optional(),
});
export type GenerateMCQInput = z.infer<typeof GenerateMCQInputSchema>;

const GenerateMCQOutputSchema = z.object({
  questions: z.array(
    z.object({
      question: z.string().describe('The multiple choice question.'),
      options: z.array(z.string()).describe('The options for the question.'),
      correctAnswer: z.string().describe('The correct answer to the question.'),
    })
  ).
describe('The generated multiple choice questions.'),
});
export type GenerateMCQOutput = z.infer<typeof GenerateMCQOutputSchema>;

export async function generateMCQ(input: GenerateMCQInput): Promise<GenerateMCQOutput> {
  return generateMCQFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMCQPrompt',
  input: {
    schema: z.object({
      topic: z.string().describe('The topic to generate MCQs for.'),
      numQuestions: z.number().describe('The number of MCQs to generate.'),
      context: z.string().describe('The context for answering the MCQs questions.'),
    }),
  },
  output: {
    schema: z.object({
      questions: z.array(
        z.object({
          question: z.string().describe('The multiple choice question.'),
          options: z.array(z.string()).describe('The options for the question.'),
          correctAnswer: z.string().describe('The correct answer to the question.'),
        })
      ).
describe('The generated multiple choice questions.'),
    }),
  },
  prompt: `You are an AI assistant designed to generate multiple-choice questions (MCQs).\n  Your task is to provide questions based on the context provided.\n  The relevant course material is given as context.\n
  <CODE_BLOCK>\n  Context:\n  {{{context}}}\n  </CODE_BLOCK>\n

  
  
  Generate {{numQuestions}} multiple choice questions on the topic of :
  \`\`\`{{{topic}}}\`\`\`

  Each question should have 4 options, with one correct answer.
  The options should be plausible distractors, testing the student's knowledge of the topic.

  Format the output as a JSON array of questions. Each question object in the array should have the following keys:
  - question: The multiple choice question.
  - options: An array of 4 strings, representing the options for the question.
  - correctAnswer: The correct answer to the question. This should be one of the strings in the options array.
  `,
});

const generateMCQFlow = ai.defineFlow<
  typeof GenerateMCQInputSchema,
  typeof GenerateMCQOutputSchema
>({
  name: 'generateMCQFlow',
  inputSchema: GenerateMCQInputSchema,
  outputSchema: GenerateMCQOutputSchema,
}, async input => {
    let context: string = '';
    switch (input.grade) {
        case 'grade-8':
            context = `
      Grade 8 Subjects:
      - Mathematics: Algebra, Geometry, Data Handling
      - Science: Physics (Forces, Motion), Chemistry (Elements, Compounds), Biology (Cells, Systems)
      - English: Literature, Grammar
      - History: Modern World History
    `;
            break;
        case 'grade-6':
            context = `
      Grade 6 Subjects:
      - Mathematics: Fractions, Decimals, Ratios
      - Science: Simple Machines, Living Things
      - English: Reading Comprehension, Creative Writing
      - Geography: Continents and Oceans
    `;
            break;
        case 'grade-4':
            context = `
      Grade 4 Subjects:
      - Mathematics: Addition, Subtraction, Introduction to Multiplication
      - Science: Animals, Plants, Environment
      - English: Vocabulary Building, Sentence Formation
      - Social Studies: Communities and Citizenship
    `;
            break;
        default:
            context = `The student is in an unspecified grade, please provide answer based on the best information you know.`;
            break;
    }
    const {output} = await prompt({...input, context});
    return output!;
});
